/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnauthorizedRouteImport } from './routes/unauthorized'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthIndexRouteImport } from './routes/auth/index'
import { Route as AuthVerifyEmailRouteImport } from './routes/auth/verify-email'
import { Route as AuthSessionExpiredRouteImport } from './routes/auth/session-expired'
import { Route as AuthResetPasswordRouteImport } from './routes/auth/reset-password'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth/forgot-password'
import { Route as AuthAcceptInvitationRouteImport } from './routes/auth/accept-invitation'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedAppIndexRouteImport } from './routes/_authenticated/app/index'
import { Route as AuthenticatedAppTasksRouteImport } from './routes/_authenticated/app/tasks'
import { Route as AuthenticatedAppSprintsRouteImport } from './routes/_authenticated/app/sprints'
import { Route as AuthenticatedAppReportReviewRouteImport } from './routes/_authenticated/app/report-review'
import { Route as AuthenticatedAppProjectsRouteImport } from './routes/_authenticated/app/projects'
import { Route as AuthenticatedAppMiddayRouteImport } from './routes/_authenticated/app/midday'
import { Route as AuthenticatedAppManagerRouteImport } from './routes/_authenticated/app/manager'
import { Route as AuthenticatedAppIntegrationsRouteImport } from './routes/_authenticated/app/integrations'
import { Route as AuthenticatedAppHrRouteImport } from './routes/_authenticated/app/hr'
import { Route as AuthenticatedAppExecutiveRouteImport } from './routes/_authenticated/app/executive'
import { Route as AuthenticatedAppDependenciesRouteImport } from './routes/_authenticated/app/dependencies'
import { Route as AuthenticatedAppCheckInRouteImport } from './routes/_authenticated/app/check-in'
import { Route as AuthenticatedAppAuditRouteImport } from './routes/_authenticated/app/audit'
import { Route as AuthenticatedAppAnalyticsRouteImport } from './routes/_authenticated/app/analytics'
import { Route as AuthenticatedAppAdminRouteImport } from './routes/_authenticated/app/admin'
import { Route as AuthenticatedAppTasksIndexRouteImport } from './routes/_authenticated/app/tasks.index'
import { Route as AuthenticatedAppSprintsIndexRouteImport } from './routes/_authenticated/app/sprints.index'
import { Route as AuthenticatedAppProjectsIndexRouteImport } from './routes/_authenticated/app/projects.index'
import { Route as AuthenticatedAppNotificationsIndexRouteImport } from './routes/_authenticated/app/notifications.index'
import { Route as AuthenticatedAppHrIndexRouteImport } from './routes/_authenticated/app/hr.index'
import { Route as AuthenticatedAppEodIndexRouteImport } from './routes/_authenticated/app/eod.index'
import { Route as AuthenticatedAppDependenciesIndexRouteImport } from './routes/_authenticated/app/dependencies.index'
import { Route as AuthenticatedAppAttendanceIndexRouteImport } from './routes/_authenticated/app/attendance/index'
import { Route as AuthenticatedAppAnalyticsIndexRouteImport } from './routes/_authenticated/app/analytics.index'
import { Route as AuthenticatedAppTasksTimeRouteImport } from './routes/_authenticated/app/tasks.time'
import { Route as AuthenticatedAppTasksKanbanRouteImport } from './routes/_authenticated/app/tasks.kanban'
import { Route as AuthenticatedAppTasksAllRouteImport } from './routes/_authenticated/app/tasks.all'
import { Route as AuthenticatedAppTasksIdRouteImport } from './routes/_authenticated/app/tasks.$id'
import { Route as AuthenticatedAppSprintsIdRouteImport } from './routes/_authenticated/app/sprints.$id'
import { Route as AuthenticatedAppProjectsWorkspaceRouteImport } from './routes/_authenticated/app/projects.workspace'
import { Route as AuthenticatedAppProjectsTemplatesRouteImport } from './routes/_authenticated/app/projects.templates'
import { Route as AuthenticatedAppProjectsClientsRouteImport } from './routes/_authenticated/app/projects.clients'
import { Route as AuthenticatedAppProjectsAllRouteImport } from './routes/_authenticated/app/projects.all'
import { Route as AuthenticatedAppProjectsIdRouteImport } from './routes/_authenticated/app/projects.$id'
import { Route as AuthenticatedAppNotificationsPreferencesRouteImport } from './routes/_authenticated/app/notifications.preferences'
import { Route as AuthenticatedAppHrOrganizationRouteImport } from './routes/_authenticated/app/hr.organization'
import { Route as AuthenticatedAppHrOnboardingRouteImport } from './routes/_authenticated/app/hr.onboarding'
import { Route as AuthenticatedAppHrOffboardingRouteImport } from './routes/_authenticated/app/hr.offboarding'
import { Route as AuthenticatedAppHrLeaveRouteImport } from './routes/_authenticated/app/hr.leave'
import { Route as AuthenticatedAppHrInvitationsRouteImport } from './routes/_authenticated/app/hr.invitations'
import { Route as AuthenticatedAppHrDocumentsRouteImport } from './routes/_authenticated/app/hr.documents'
import { Route as AuthenticatedAppHrAuditRouteImport } from './routes/_authenticated/app/hr.audit'
import { Route as AuthenticatedAppHrAnnouncementsRouteImport } from './routes/_authenticated/app/hr.announcements'
import { Route as AuthenticatedAppEodHistoryRouteImport } from './routes/_authenticated/app/eod.history'
import { Route as AuthenticatedAppDependenciesManagerRouteImport } from './routes/_authenticated/app/dependencies.manager'
import { Route as AuthenticatedAppDependenciesIdRouteImport } from './routes/_authenticated/app/dependencies.$id'
import { Route as AuthenticatedAppAttendanceTeamRouteImport } from './routes/_authenticated/app/attendance/team'
import { Route as AuthenticatedAppAnalyticsTeamRouteImport } from './routes/_authenticated/app/analytics.team'
import { Route as AuthenticatedAppAnalyticsSavedRouteImport } from './routes/_authenticated/app/analytics.saved'
import { Route as AuthenticatedAppAnalyticsHrRouteImport } from './routes/_authenticated/app/analytics.hr'
import { Route as AuthenticatedAppAnalyticsExecutiveRouteImport } from './routes/_authenticated/app/analytics.executive'
import { Route as AuthenticatedAppHrEmployeesIndexRouteImport } from './routes/_authenticated/app/hr.employees.index'
import { Route as AuthenticatedAppProjectsClientsIdRouteImport } from './routes/_authenticated/app/projects.clients.$id'
import { Route as AuthenticatedAppHrEmployeesIdRouteImport } from './routes/_authenticated/app/hr.employees.$id'

const UnauthorizedRoute = UnauthorizedRouteImport.update({
  id: '/unauthorized',
  path: '/unauthorized',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/auth/',
  path: '/auth/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthVerifyEmailRoute = AuthVerifyEmailRouteImport.update({
  id: '/auth/verify-email',
  path: '/auth/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSessionExpiredRoute = AuthSessionExpiredRouteImport.update({
  id: '/auth/session-expired',
  path: '/auth/session-expired',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/auth/reset-password',
  path: '/auth/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/auth/forgot-password',
  path: '/auth/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthAcceptInvitationRoute = AuthAcceptInvitationRouteImport.update({
  id: '/auth/accept-invitation',
  path: '/auth/accept-invitation',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppIndexRoute = AuthenticatedAppIndexRouteImport.update({
  id: '/app/',
  path: '/app/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppTasksRoute = AuthenticatedAppTasksRouteImport.update({
  id: '/app/tasks',
  path: '/app/tasks',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppSprintsRoute = AuthenticatedAppSprintsRouteImport.update({
  id: '/app/sprints',
  path: '/app/sprints',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppReportReviewRoute =
  AuthenticatedAppReportReviewRouteImport.update({
    id: '/app/report-review',
    path: '/app/report-review',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppProjectsRoute =
  AuthenticatedAppProjectsRouteImport.update({
    id: '/app/projects',
    path: '/app/projects',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppMiddayRoute = AuthenticatedAppMiddayRouteImport.update({
  id: '/app/midday',
  path: '/app/midday',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppManagerRoute = AuthenticatedAppManagerRouteImport.update({
  id: '/app/manager',
  path: '/app/manager',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppIntegrationsRoute =
  AuthenticatedAppIntegrationsRouteImport.update({
    id: '/app/integrations',
    path: '/app/integrations',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppHrRoute = AuthenticatedAppHrRouteImport.update({
  id: '/app/hr',
  path: '/app/hr',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppExecutiveRoute =
  AuthenticatedAppExecutiveRouteImport.update({
    id: '/app/executive',
    path: '/app/executive',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppDependenciesRoute =
  AuthenticatedAppDependenciesRouteImport.update({
    id: '/app/dependencies',
    path: '/app/dependencies',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppCheckInRoute = AuthenticatedAppCheckInRouteImport.update({
  id: '/app/check-in',
  path: '/app/check-in',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppAuditRoute = AuthenticatedAppAuditRouteImport.update({
  id: '/app/audit',
  path: '/app/audit',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppAnalyticsRoute =
  AuthenticatedAppAnalyticsRouteImport.update({
    id: '/app/analytics',
    path: '/app/analytics',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppAdminRoute = AuthenticatedAppAdminRouteImport.update({
  id: '/app/admin',
  path: '/app/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppTasksIndexRoute =
  AuthenticatedAppTasksIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAppTasksRoute,
  } as any)
const AuthenticatedAppSprintsIndexRoute =
  AuthenticatedAppSprintsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAppSprintsRoute,
  } as any)
const AuthenticatedAppProjectsIndexRoute =
  AuthenticatedAppProjectsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAppProjectsRoute,
  } as any)
const AuthenticatedAppNotificationsIndexRoute =
  AuthenticatedAppNotificationsIndexRouteImport.update({
    id: '/app/notifications/',
    path: '/app/notifications/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppHrIndexRoute = AuthenticatedAppHrIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAppHrRoute,
} as any)
const AuthenticatedAppEodIndexRoute =
  AuthenticatedAppEodIndexRouteImport.update({
    id: '/app/eod/',
    path: '/app/eod/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppDependenciesIndexRoute =
  AuthenticatedAppDependenciesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAppDependenciesRoute,
  } as any)
const AuthenticatedAppAttendanceIndexRoute =
  AuthenticatedAppAttendanceIndexRouteImport.update({
    id: '/app/attendance/',
    path: '/app/attendance/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppAnalyticsIndexRoute =
  AuthenticatedAppAnalyticsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAppAnalyticsRoute,
  } as any)
const AuthenticatedAppTasksTimeRoute =
  AuthenticatedAppTasksTimeRouteImport.update({
    id: '/time',
    path: '/time',
    getParentRoute: () => AuthenticatedAppTasksRoute,
  } as any)
const AuthenticatedAppTasksKanbanRoute =
  AuthenticatedAppTasksKanbanRouteImport.update({
    id: '/kanban',
    path: '/kanban',
    getParentRoute: () => AuthenticatedAppTasksRoute,
  } as any)
const AuthenticatedAppTasksAllRoute =
  AuthenticatedAppTasksAllRouteImport.update({
    id: '/all',
    path: '/all',
    getParentRoute: () => AuthenticatedAppTasksRoute,
  } as any)
const AuthenticatedAppTasksIdRoute = AuthenticatedAppTasksIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedAppTasksRoute,
} as any)
const AuthenticatedAppSprintsIdRoute =
  AuthenticatedAppSprintsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedAppSprintsRoute,
  } as any)
const AuthenticatedAppProjectsWorkspaceRoute =
  AuthenticatedAppProjectsWorkspaceRouteImport.update({
    id: '/workspace',
    path: '/workspace',
    getParentRoute: () => AuthenticatedAppProjectsRoute,
  } as any)
const AuthenticatedAppProjectsTemplatesRoute =
  AuthenticatedAppProjectsTemplatesRouteImport.update({
    id: '/templates',
    path: '/templates',
    getParentRoute: () => AuthenticatedAppProjectsRoute,
  } as any)
const AuthenticatedAppProjectsClientsRoute =
  AuthenticatedAppProjectsClientsRouteImport.update({
    id: '/clients',
    path: '/clients',
    getParentRoute: () => AuthenticatedAppProjectsRoute,
  } as any)
const AuthenticatedAppProjectsAllRoute =
  AuthenticatedAppProjectsAllRouteImport.update({
    id: '/all',
    path: '/all',
    getParentRoute: () => AuthenticatedAppProjectsRoute,
  } as any)
const AuthenticatedAppProjectsIdRoute =
  AuthenticatedAppProjectsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedAppProjectsRoute,
  } as any)
const AuthenticatedAppNotificationsPreferencesRoute =
  AuthenticatedAppNotificationsPreferencesRouteImport.update({
    id: '/app/notifications/preferences',
    path: '/app/notifications/preferences',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppHrOrganizationRoute =
  AuthenticatedAppHrOrganizationRouteImport.update({
    id: '/organization',
    path: '/organization',
    getParentRoute: () => AuthenticatedAppHrRoute,
  } as any)
const AuthenticatedAppHrOnboardingRoute =
  AuthenticatedAppHrOnboardingRouteImport.update({
    id: '/onboarding',
    path: '/onboarding',
    getParentRoute: () => AuthenticatedAppHrRoute,
  } as any)
const AuthenticatedAppHrOffboardingRoute =
  AuthenticatedAppHrOffboardingRouteImport.update({
    id: '/offboarding',
    path: '/offboarding',
    getParentRoute: () => AuthenticatedAppHrRoute,
  } as any)
const AuthenticatedAppHrLeaveRoute = AuthenticatedAppHrLeaveRouteImport.update({
  id: '/leave',
  path: '/leave',
  getParentRoute: () => AuthenticatedAppHrRoute,
} as any)
const AuthenticatedAppHrInvitationsRoute =
  AuthenticatedAppHrInvitationsRouteImport.update({
    id: '/invitations',
    path: '/invitations',
    getParentRoute: () => AuthenticatedAppHrRoute,
  } as any)
const AuthenticatedAppHrDocumentsRoute =
  AuthenticatedAppHrDocumentsRouteImport.update({
    id: '/documents',
    path: '/documents',
    getParentRoute: () => AuthenticatedAppHrRoute,
  } as any)
const AuthenticatedAppHrAuditRoute = AuthenticatedAppHrAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AuthenticatedAppHrRoute,
} as any)
const AuthenticatedAppHrAnnouncementsRoute =
  AuthenticatedAppHrAnnouncementsRouteImport.update({
    id: '/announcements',
    path: '/announcements',
    getParentRoute: () => AuthenticatedAppHrRoute,
  } as any)
const AuthenticatedAppEodHistoryRoute =
  AuthenticatedAppEodHistoryRouteImport.update({
    id: '/app/eod/history',
    path: '/app/eod/history',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppDependenciesManagerRoute =
  AuthenticatedAppDependenciesManagerRouteImport.update({
    id: '/manager',
    path: '/manager',
    getParentRoute: () => AuthenticatedAppDependenciesRoute,
  } as any)
const AuthenticatedAppDependenciesIdRoute =
  AuthenticatedAppDependenciesIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedAppDependenciesRoute,
  } as any)
const AuthenticatedAppAttendanceTeamRoute =
  AuthenticatedAppAttendanceTeamRouteImport.update({
    id: '/app/attendance/team',
    path: '/app/attendance/team',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppAnalyticsTeamRoute =
  AuthenticatedAppAnalyticsTeamRouteImport.update({
    id: '/team',
    path: '/team',
    getParentRoute: () => AuthenticatedAppAnalyticsRoute,
  } as any)
const AuthenticatedAppAnalyticsSavedRoute =
  AuthenticatedAppAnalyticsSavedRouteImport.update({
    id: '/saved',
    path: '/saved',
    getParentRoute: () => AuthenticatedAppAnalyticsRoute,
  } as any)
const AuthenticatedAppAnalyticsHrRoute =
  AuthenticatedAppAnalyticsHrRouteImport.update({
    id: '/hr',
    path: '/hr',
    getParentRoute: () => AuthenticatedAppAnalyticsRoute,
  } as any)
const AuthenticatedAppAnalyticsExecutiveRoute =
  AuthenticatedAppAnalyticsExecutiveRouteImport.update({
    id: '/executive',
    path: '/executive',
    getParentRoute: () => AuthenticatedAppAnalyticsRoute,
  } as any)
const AuthenticatedAppHrEmployeesIndexRoute =
  AuthenticatedAppHrEmployeesIndexRouteImport.update({
    id: '/employees/',
    path: '/employees/',
    getParentRoute: () => AuthenticatedAppHrRoute,
  } as any)
const AuthenticatedAppProjectsClientsIdRoute =
  AuthenticatedAppProjectsClientsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedAppProjectsClientsRoute,
  } as any)
const AuthenticatedAppHrEmployeesIdRoute =
  AuthenticatedAppHrEmployeesIdRouteImport.update({
    id: '/employees/$id',
    path: '/employees/$id',
    getParentRoute: () => AuthenticatedAppHrRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/auth/accept-invitation': typeof AuthAcceptInvitationRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/session-expired': typeof AuthSessionExpiredRoute
  '/auth/verify-email': typeof AuthVerifyEmailRoute
  '/auth/': typeof AuthIndexRoute
  '/app/admin': typeof AuthenticatedAppAdminRoute
  '/app/analytics': typeof AuthenticatedAppAnalyticsRouteWithChildren
  '/app/audit': typeof AuthenticatedAppAuditRoute
  '/app/check-in': typeof AuthenticatedAppCheckInRoute
  '/app/dependencies': typeof AuthenticatedAppDependenciesRouteWithChildren
  '/app/executive': typeof AuthenticatedAppExecutiveRoute
  '/app/hr': typeof AuthenticatedAppHrRouteWithChildren
  '/app/integrations': typeof AuthenticatedAppIntegrationsRoute
  '/app/manager': typeof AuthenticatedAppManagerRoute
  '/app/midday': typeof AuthenticatedAppMiddayRoute
  '/app/projects': typeof AuthenticatedAppProjectsRouteWithChildren
  '/app/report-review': typeof AuthenticatedAppReportReviewRoute
  '/app/sprints': typeof AuthenticatedAppSprintsRouteWithChildren
  '/app/tasks': typeof AuthenticatedAppTasksRouteWithChildren
  '/app/': typeof AuthenticatedAppIndexRoute
  '/app/analytics/executive': typeof AuthenticatedAppAnalyticsExecutiveRoute
  '/app/analytics/hr': typeof AuthenticatedAppAnalyticsHrRoute
  '/app/analytics/saved': typeof AuthenticatedAppAnalyticsSavedRoute
  '/app/analytics/team': typeof AuthenticatedAppAnalyticsTeamRoute
  '/app/attendance/team': typeof AuthenticatedAppAttendanceTeamRoute
  '/app/dependencies/$id': typeof AuthenticatedAppDependenciesIdRoute
  '/app/dependencies/manager': typeof AuthenticatedAppDependenciesManagerRoute
  '/app/eod/history': typeof AuthenticatedAppEodHistoryRoute
  '/app/hr/announcements': typeof AuthenticatedAppHrAnnouncementsRoute
  '/app/hr/audit': typeof AuthenticatedAppHrAuditRoute
  '/app/hr/documents': typeof AuthenticatedAppHrDocumentsRoute
  '/app/hr/invitations': typeof AuthenticatedAppHrInvitationsRoute
  '/app/hr/leave': typeof AuthenticatedAppHrLeaveRoute
  '/app/hr/offboarding': typeof AuthenticatedAppHrOffboardingRoute
  '/app/hr/onboarding': typeof AuthenticatedAppHrOnboardingRoute
  '/app/hr/organization': typeof AuthenticatedAppHrOrganizationRoute
  '/app/notifications/preferences': typeof AuthenticatedAppNotificationsPreferencesRoute
  '/app/projects/$id': typeof AuthenticatedAppProjectsIdRoute
  '/app/projects/all': typeof AuthenticatedAppProjectsAllRoute
  '/app/projects/clients': typeof AuthenticatedAppProjectsClientsRouteWithChildren
  '/app/projects/templates': typeof AuthenticatedAppProjectsTemplatesRoute
  '/app/projects/workspace': typeof AuthenticatedAppProjectsWorkspaceRoute
  '/app/sprints/$id': typeof AuthenticatedAppSprintsIdRoute
  '/app/tasks/$id': typeof AuthenticatedAppTasksIdRoute
  '/app/tasks/all': typeof AuthenticatedAppTasksAllRoute
  '/app/tasks/kanban': typeof AuthenticatedAppTasksKanbanRoute
  '/app/tasks/time': typeof AuthenticatedAppTasksTimeRoute
  '/app/analytics/': typeof AuthenticatedAppAnalyticsIndexRoute
  '/app/attendance/': typeof AuthenticatedAppAttendanceIndexRoute
  '/app/dependencies/': typeof AuthenticatedAppDependenciesIndexRoute
  '/app/eod/': typeof AuthenticatedAppEodIndexRoute
  '/app/hr/': typeof AuthenticatedAppHrIndexRoute
  '/app/notifications/': typeof AuthenticatedAppNotificationsIndexRoute
  '/app/projects/': typeof AuthenticatedAppProjectsIndexRoute
  '/app/sprints/': typeof AuthenticatedAppSprintsIndexRoute
  '/app/tasks/': typeof AuthenticatedAppTasksIndexRoute
  '/app/hr/employees/$id': typeof AuthenticatedAppHrEmployeesIdRoute
  '/app/projects/clients/$id': typeof AuthenticatedAppProjectsClientsIdRoute
  '/app/hr/employees/': typeof AuthenticatedAppHrEmployeesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/auth/accept-invitation': typeof AuthAcceptInvitationRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/session-expired': typeof AuthSessionExpiredRoute
  '/auth/verify-email': typeof AuthVerifyEmailRoute
  '/auth': typeof AuthIndexRoute
  '/app/admin': typeof AuthenticatedAppAdminRoute
  '/app/audit': typeof AuthenticatedAppAuditRoute
  '/app/check-in': typeof AuthenticatedAppCheckInRoute
  '/app/executive': typeof AuthenticatedAppExecutiveRoute
  '/app/integrations': typeof AuthenticatedAppIntegrationsRoute
  '/app/manager': typeof AuthenticatedAppManagerRoute
  '/app/midday': typeof AuthenticatedAppMiddayRoute
  '/app/report-review': typeof AuthenticatedAppReportReviewRoute
  '/app': typeof AuthenticatedAppIndexRoute
  '/app/analytics/executive': typeof AuthenticatedAppAnalyticsExecutiveRoute
  '/app/analytics/hr': typeof AuthenticatedAppAnalyticsHrRoute
  '/app/analytics/saved': typeof AuthenticatedAppAnalyticsSavedRoute
  '/app/analytics/team': typeof AuthenticatedAppAnalyticsTeamRoute
  '/app/attendance/team': typeof AuthenticatedAppAttendanceTeamRoute
  '/app/dependencies/$id': typeof AuthenticatedAppDependenciesIdRoute
  '/app/dependencies/manager': typeof AuthenticatedAppDependenciesManagerRoute
  '/app/eod/history': typeof AuthenticatedAppEodHistoryRoute
  '/app/hr/announcements': typeof AuthenticatedAppHrAnnouncementsRoute
  '/app/hr/audit': typeof AuthenticatedAppHrAuditRoute
  '/app/hr/documents': typeof AuthenticatedAppHrDocumentsRoute
  '/app/hr/invitations': typeof AuthenticatedAppHrInvitationsRoute
  '/app/hr/leave': typeof AuthenticatedAppHrLeaveRoute
  '/app/hr/offboarding': typeof AuthenticatedAppHrOffboardingRoute
  '/app/hr/onboarding': typeof AuthenticatedAppHrOnboardingRoute
  '/app/hr/organization': typeof AuthenticatedAppHrOrganizationRoute
  '/app/notifications/preferences': typeof AuthenticatedAppNotificationsPreferencesRoute
  '/app/projects/$id': typeof AuthenticatedAppProjectsIdRoute
  '/app/projects/all': typeof AuthenticatedAppProjectsAllRoute
  '/app/projects/clients': typeof AuthenticatedAppProjectsClientsRouteWithChildren
  '/app/projects/templates': typeof AuthenticatedAppProjectsTemplatesRoute
  '/app/projects/workspace': typeof AuthenticatedAppProjectsWorkspaceRoute
  '/app/sprints/$id': typeof AuthenticatedAppSprintsIdRoute
  '/app/tasks/$id': typeof AuthenticatedAppTasksIdRoute
  '/app/tasks/all': typeof AuthenticatedAppTasksAllRoute
  '/app/tasks/kanban': typeof AuthenticatedAppTasksKanbanRoute
  '/app/tasks/time': typeof AuthenticatedAppTasksTimeRoute
  '/app/analytics': typeof AuthenticatedAppAnalyticsIndexRoute
  '/app/attendance': typeof AuthenticatedAppAttendanceIndexRoute
  '/app/dependencies': typeof AuthenticatedAppDependenciesIndexRoute
  '/app/eod': typeof AuthenticatedAppEodIndexRoute
  '/app/hr': typeof AuthenticatedAppHrIndexRoute
  '/app/notifications': typeof AuthenticatedAppNotificationsIndexRoute
  '/app/projects': typeof AuthenticatedAppProjectsIndexRoute
  '/app/sprints': typeof AuthenticatedAppSprintsIndexRoute
  '/app/tasks': typeof AuthenticatedAppTasksIndexRoute
  '/app/hr/employees/$id': typeof AuthenticatedAppHrEmployeesIdRoute
  '/app/projects/clients/$id': typeof AuthenticatedAppProjectsClientsIdRoute
  '/app/hr/employees': typeof AuthenticatedAppHrEmployeesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/unauthorized': typeof UnauthorizedRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/auth/accept-invitation': typeof AuthAcceptInvitationRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/session-expired': typeof AuthSessionExpiredRoute
  '/auth/verify-email': typeof AuthVerifyEmailRoute
  '/auth/': typeof AuthIndexRoute
  '/_authenticated/app/admin': typeof AuthenticatedAppAdminRoute
  '/_authenticated/app/analytics': typeof AuthenticatedAppAnalyticsRouteWithChildren
  '/_authenticated/app/audit': typeof AuthenticatedAppAuditRoute
  '/_authenticated/app/check-in': typeof AuthenticatedAppCheckInRoute
  '/_authenticated/app/dependencies': typeof AuthenticatedAppDependenciesRouteWithChildren
  '/_authenticated/app/executive': typeof AuthenticatedAppExecutiveRoute
  '/_authenticated/app/hr': typeof AuthenticatedAppHrRouteWithChildren
  '/_authenticated/app/integrations': typeof AuthenticatedAppIntegrationsRoute
  '/_authenticated/app/manager': typeof AuthenticatedAppManagerRoute
  '/_authenticated/app/midday': typeof AuthenticatedAppMiddayRoute
  '/_authenticated/app/projects': typeof AuthenticatedAppProjectsRouteWithChildren
  '/_authenticated/app/report-review': typeof AuthenticatedAppReportReviewRoute
  '/_authenticated/app/sprints': typeof AuthenticatedAppSprintsRouteWithChildren
  '/_authenticated/app/tasks': typeof AuthenticatedAppTasksRouteWithChildren
  '/_authenticated/app/': typeof AuthenticatedAppIndexRoute
  '/_authenticated/app/analytics/executive': typeof AuthenticatedAppAnalyticsExecutiveRoute
  '/_authenticated/app/analytics/hr': typeof AuthenticatedAppAnalyticsHrRoute
  '/_authenticated/app/analytics/saved': typeof AuthenticatedAppAnalyticsSavedRoute
  '/_authenticated/app/analytics/team': typeof AuthenticatedAppAnalyticsTeamRoute
  '/_authenticated/app/attendance/team': typeof AuthenticatedAppAttendanceTeamRoute
  '/_authenticated/app/dependencies/$id': typeof AuthenticatedAppDependenciesIdRoute
  '/_authenticated/app/dependencies/manager': typeof AuthenticatedAppDependenciesManagerRoute
  '/_authenticated/app/eod/history': typeof AuthenticatedAppEodHistoryRoute
  '/_authenticated/app/hr/announcements': typeof AuthenticatedAppHrAnnouncementsRoute
  '/_authenticated/app/hr/audit': typeof AuthenticatedAppHrAuditRoute
  '/_authenticated/app/hr/documents': typeof AuthenticatedAppHrDocumentsRoute
  '/_authenticated/app/hr/invitations': typeof AuthenticatedAppHrInvitationsRoute
  '/_authenticated/app/hr/leave': typeof AuthenticatedAppHrLeaveRoute
  '/_authenticated/app/hr/offboarding': typeof AuthenticatedAppHrOffboardingRoute
  '/_authenticated/app/hr/onboarding': typeof AuthenticatedAppHrOnboardingRoute
  '/_authenticated/app/hr/organization': typeof AuthenticatedAppHrOrganizationRoute
  '/_authenticated/app/notifications/preferences': typeof AuthenticatedAppNotificationsPreferencesRoute
  '/_authenticated/app/projects/$id': typeof AuthenticatedAppProjectsIdRoute
  '/_authenticated/app/projects/all': typeof AuthenticatedAppProjectsAllRoute
  '/_authenticated/app/projects/clients': typeof AuthenticatedAppProjectsClientsRouteWithChildren
  '/_authenticated/app/projects/templates': typeof AuthenticatedAppProjectsTemplatesRoute
  '/_authenticated/app/projects/workspace': typeof AuthenticatedAppProjectsWorkspaceRoute
  '/_authenticated/app/sprints/$id': typeof AuthenticatedAppSprintsIdRoute
  '/_authenticated/app/tasks/$id': typeof AuthenticatedAppTasksIdRoute
  '/_authenticated/app/tasks/all': typeof AuthenticatedAppTasksAllRoute
  '/_authenticated/app/tasks/kanban': typeof AuthenticatedAppTasksKanbanRoute
  '/_authenticated/app/tasks/time': typeof AuthenticatedAppTasksTimeRoute
  '/_authenticated/app/analytics/': typeof AuthenticatedAppAnalyticsIndexRoute
  '/_authenticated/app/attendance/': typeof AuthenticatedAppAttendanceIndexRoute
  '/_authenticated/app/dependencies/': typeof AuthenticatedAppDependenciesIndexRoute
  '/_authenticated/app/eod/': typeof AuthenticatedAppEodIndexRoute
  '/_authenticated/app/hr/': typeof AuthenticatedAppHrIndexRoute
  '/_authenticated/app/notifications/': typeof AuthenticatedAppNotificationsIndexRoute
  '/_authenticated/app/projects/': typeof AuthenticatedAppProjectsIndexRoute
  '/_authenticated/app/sprints/': typeof AuthenticatedAppSprintsIndexRoute
  '/_authenticated/app/tasks/': typeof AuthenticatedAppTasksIndexRoute
  '/_authenticated/app/hr/employees/$id': typeof AuthenticatedAppHrEmployeesIdRoute
  '/_authenticated/app/projects/clients/$id': typeof AuthenticatedAppProjectsClientsIdRoute
  '/_authenticated/app/hr/employees/': typeof AuthenticatedAppHrEmployeesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/unauthorized'
    | '/settings'
    | '/auth/accept-invitation'
    | '/auth/forgot-password'
    | '/auth/reset-password'
    | '/auth/session-expired'
    | '/auth/verify-email'
    | '/auth/'
    | '/app/admin'
    | '/app/analytics'
    | '/app/audit'
    | '/app/check-in'
    | '/app/dependencies'
    | '/app/executive'
    | '/app/hr'
    | '/app/integrations'
    | '/app/manager'
    | '/app/midday'
    | '/app/projects'
    | '/app/report-review'
    | '/app/sprints'
    | '/app/tasks'
    | '/app/'
    | '/app/analytics/executive'
    | '/app/analytics/hr'
    | '/app/analytics/saved'
    | '/app/analytics/team'
    | '/app/attendance/team'
    | '/app/dependencies/$id'
    | '/app/dependencies/manager'
    | '/app/eod/history'
    | '/app/hr/announcements'
    | '/app/hr/audit'
    | '/app/hr/documents'
    | '/app/hr/invitations'
    | '/app/hr/leave'
    | '/app/hr/offboarding'
    | '/app/hr/onboarding'
    | '/app/hr/organization'
    | '/app/notifications/preferences'
    | '/app/projects/$id'
    | '/app/projects/all'
    | '/app/projects/clients'
    | '/app/projects/templates'
    | '/app/projects/workspace'
    | '/app/sprints/$id'
    | '/app/tasks/$id'
    | '/app/tasks/all'
    | '/app/tasks/kanban'
    | '/app/tasks/time'
    | '/app/analytics/'
    | '/app/attendance/'
    | '/app/dependencies/'
    | '/app/eod/'
    | '/app/hr/'
    | '/app/notifications/'
    | '/app/projects/'
    | '/app/sprints/'
    | '/app/tasks/'
    | '/app/hr/employees/$id'
    | '/app/projects/clients/$id'
    | '/app/hr/employees/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/unauthorized'
    | '/settings'
    | '/auth/accept-invitation'
    | '/auth/forgot-password'
    | '/auth/reset-password'
    | '/auth/session-expired'
    | '/auth/verify-email'
    | '/auth'
    | '/app/admin'
    | '/app/audit'
    | '/app/check-in'
    | '/app/executive'
    | '/app/integrations'
    | '/app/manager'
    | '/app/midday'
    | '/app/report-review'
    | '/app'
    | '/app/analytics/executive'
    | '/app/analytics/hr'
    | '/app/analytics/saved'
    | '/app/analytics/team'
    | '/app/attendance/team'
    | '/app/dependencies/$id'
    | '/app/dependencies/manager'
    | '/app/eod/history'
    | '/app/hr/announcements'
    | '/app/hr/audit'
    | '/app/hr/documents'
    | '/app/hr/invitations'
    | '/app/hr/leave'
    | '/app/hr/offboarding'
    | '/app/hr/onboarding'
    | '/app/hr/organization'
    | '/app/notifications/preferences'
    | '/app/projects/$id'
    | '/app/projects/all'
    | '/app/projects/clients'
    | '/app/projects/templates'
    | '/app/projects/workspace'
    | '/app/sprints/$id'
    | '/app/tasks/$id'
    | '/app/tasks/all'
    | '/app/tasks/kanban'
    | '/app/tasks/time'
    | '/app/analytics'
    | '/app/attendance'
    | '/app/dependencies'
    | '/app/eod'
    | '/app/hr'
    | '/app/notifications'
    | '/app/projects'
    | '/app/sprints'
    | '/app/tasks'
    | '/app/hr/employees/$id'
    | '/app/projects/clients/$id'
    | '/app/hr/employees'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/unauthorized'
    | '/_authenticated/settings'
    | '/auth/accept-invitation'
    | '/auth/forgot-password'
    | '/auth/reset-password'
    | '/auth/session-expired'
    | '/auth/verify-email'
    | '/auth/'
    | '/_authenticated/app/admin'
    | '/_authenticated/app/analytics'
    | '/_authenticated/app/audit'
    | '/_authenticated/app/check-in'
    | '/_authenticated/app/dependencies'
    | '/_authenticated/app/executive'
    | '/_authenticated/app/hr'
    | '/_authenticated/app/integrations'
    | '/_authenticated/app/manager'
    | '/_authenticated/app/midday'
    | '/_authenticated/app/projects'
    | '/_authenticated/app/report-review'
    | '/_authenticated/app/sprints'
    | '/_authenticated/app/tasks'
    | '/_authenticated/app/'
    | '/_authenticated/app/analytics/executive'
    | '/_authenticated/app/analytics/hr'
    | '/_authenticated/app/analytics/saved'
    | '/_authenticated/app/analytics/team'
    | '/_authenticated/app/attendance/team'
    | '/_authenticated/app/dependencies/$id'
    | '/_authenticated/app/dependencies/manager'
    | '/_authenticated/app/eod/history'
    | '/_authenticated/app/hr/announcements'
    | '/_authenticated/app/hr/audit'
    | '/_authenticated/app/hr/documents'
    | '/_authenticated/app/hr/invitations'
    | '/_authenticated/app/hr/leave'
    | '/_authenticated/app/hr/offboarding'
    | '/_authenticated/app/hr/onboarding'
    | '/_authenticated/app/hr/organization'
    | '/_authenticated/app/notifications/preferences'
    | '/_authenticated/app/projects/$id'
    | '/_authenticated/app/projects/all'
    | '/_authenticated/app/projects/clients'
    | '/_authenticated/app/projects/templates'
    | '/_authenticated/app/projects/workspace'
    | '/_authenticated/app/sprints/$id'
    | '/_authenticated/app/tasks/$id'
    | '/_authenticated/app/tasks/all'
    | '/_authenticated/app/tasks/kanban'
    | '/_authenticated/app/tasks/time'
    | '/_authenticated/app/analytics/'
    | '/_authenticated/app/attendance/'
    | '/_authenticated/app/dependencies/'
    | '/_authenticated/app/eod/'
    | '/_authenticated/app/hr/'
    | '/_authenticated/app/notifications/'
    | '/_authenticated/app/projects/'
    | '/_authenticated/app/sprints/'
    | '/_authenticated/app/tasks/'
    | '/_authenticated/app/hr/employees/$id'
    | '/_authenticated/app/projects/clients/$id'
    | '/_authenticated/app/hr/employees/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  UnauthorizedRoute: typeof UnauthorizedRoute
  AuthAcceptInvitationRoute: typeof AuthAcceptInvitationRoute
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthSessionExpiredRoute: typeof AuthSessionExpiredRoute
  AuthVerifyEmailRoute: typeof AuthVerifyEmailRoute
  AuthIndexRoute: typeof AuthIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unauthorized': {
      id: '/unauthorized'
      path: '/unauthorized'
      fullPath: '/unauthorized'
      preLoaderRoute: typeof UnauthorizedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/': {
      id: '/auth/'
      path: '/auth'
      fullPath: '/auth/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/verify-email': {
      id: '/auth/verify-email'
      path: '/auth/verify-email'
      fullPath: '/auth/verify-email'
      preLoaderRoute: typeof AuthVerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/session-expired': {
      id: '/auth/session-expired'
      path: '/auth/session-expired'
      fullPath: '/auth/session-expired'
      preLoaderRoute: typeof AuthSessionExpiredRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/auth/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/auth/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/accept-invitation': {
      id: '/auth/accept-invitation'
      path: '/auth/accept-invitation'
      fullPath: '/auth/accept-invitation'
      preLoaderRoute: typeof AuthAcceptInvitationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/': {
      id: '/_authenticated/app/'
      path: '/app'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthenticatedAppIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/tasks': {
      id: '/_authenticated/app/tasks'
      path: '/app/tasks'
      fullPath: '/app/tasks'
      preLoaderRoute: typeof AuthenticatedAppTasksRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/sprints': {
      id: '/_authenticated/app/sprints'
      path: '/app/sprints'
      fullPath: '/app/sprints'
      preLoaderRoute: typeof AuthenticatedAppSprintsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/report-review': {
      id: '/_authenticated/app/report-review'
      path: '/app/report-review'
      fullPath: '/app/report-review'
      preLoaderRoute: typeof AuthenticatedAppReportReviewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/projects': {
      id: '/_authenticated/app/projects'
      path: '/app/projects'
      fullPath: '/app/projects'
      preLoaderRoute: typeof AuthenticatedAppProjectsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/midday': {
      id: '/_authenticated/app/midday'
      path: '/app/midday'
      fullPath: '/app/midday'
      preLoaderRoute: typeof AuthenticatedAppMiddayRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/manager': {
      id: '/_authenticated/app/manager'
      path: '/app/manager'
      fullPath: '/app/manager'
      preLoaderRoute: typeof AuthenticatedAppManagerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/integrations': {
      id: '/_authenticated/app/integrations'
      path: '/app/integrations'
      fullPath: '/app/integrations'
      preLoaderRoute: typeof AuthenticatedAppIntegrationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/hr': {
      id: '/_authenticated/app/hr'
      path: '/app/hr'
      fullPath: '/app/hr'
      preLoaderRoute: typeof AuthenticatedAppHrRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/executive': {
      id: '/_authenticated/app/executive'
      path: '/app/executive'
      fullPath: '/app/executive'
      preLoaderRoute: typeof AuthenticatedAppExecutiveRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/dependencies': {
      id: '/_authenticated/app/dependencies'
      path: '/app/dependencies'
      fullPath: '/app/dependencies'
      preLoaderRoute: typeof AuthenticatedAppDependenciesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/check-in': {
      id: '/_authenticated/app/check-in'
      path: '/app/check-in'
      fullPath: '/app/check-in'
      preLoaderRoute: typeof AuthenticatedAppCheckInRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/audit': {
      id: '/_authenticated/app/audit'
      path: '/app/audit'
      fullPath: '/app/audit'
      preLoaderRoute: typeof AuthenticatedAppAuditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/analytics': {
      id: '/_authenticated/app/analytics'
      path: '/app/analytics'
      fullPath: '/app/analytics'
      preLoaderRoute: typeof AuthenticatedAppAnalyticsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/admin': {
      id: '/_authenticated/app/admin'
      path: '/app/admin'
      fullPath: '/app/admin'
      preLoaderRoute: typeof AuthenticatedAppAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/tasks/': {
      id: '/_authenticated/app/tasks/'
      path: '/'
      fullPath: '/app/tasks/'
      preLoaderRoute: typeof AuthenticatedAppTasksIndexRouteImport
      parentRoute: typeof AuthenticatedAppTasksRoute
    }
    '/_authenticated/app/sprints/': {
      id: '/_authenticated/app/sprints/'
      path: '/'
      fullPath: '/app/sprints/'
      preLoaderRoute: typeof AuthenticatedAppSprintsIndexRouteImport
      parentRoute: typeof AuthenticatedAppSprintsRoute
    }
    '/_authenticated/app/projects/': {
      id: '/_authenticated/app/projects/'
      path: '/'
      fullPath: '/app/projects/'
      preLoaderRoute: typeof AuthenticatedAppProjectsIndexRouteImport
      parentRoute: typeof AuthenticatedAppProjectsRoute
    }
    '/_authenticated/app/notifications/': {
      id: '/_authenticated/app/notifications/'
      path: '/app/notifications'
      fullPath: '/app/notifications/'
      preLoaderRoute: typeof AuthenticatedAppNotificationsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/hr/': {
      id: '/_authenticated/app/hr/'
      path: '/'
      fullPath: '/app/hr/'
      preLoaderRoute: typeof AuthenticatedAppHrIndexRouteImport
      parentRoute: typeof AuthenticatedAppHrRoute
    }
    '/_authenticated/app/eod/': {
      id: '/_authenticated/app/eod/'
      path: '/app/eod'
      fullPath: '/app/eod/'
      preLoaderRoute: typeof AuthenticatedAppEodIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/dependencies/': {
      id: '/_authenticated/app/dependencies/'
      path: '/'
      fullPath: '/app/dependencies/'
      preLoaderRoute: typeof AuthenticatedAppDependenciesIndexRouteImport
      parentRoute: typeof AuthenticatedAppDependenciesRoute
    }
    '/_authenticated/app/attendance/': {
      id: '/_authenticated/app/attendance/'
      path: '/app/attendance'
      fullPath: '/app/attendance/'
      preLoaderRoute: typeof AuthenticatedAppAttendanceIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/analytics/': {
      id: '/_authenticated/app/analytics/'
      path: '/'
      fullPath: '/app/analytics/'
      preLoaderRoute: typeof AuthenticatedAppAnalyticsIndexRouteImport
      parentRoute: typeof AuthenticatedAppAnalyticsRoute
    }
    '/_authenticated/app/tasks/time': {
      id: '/_authenticated/app/tasks/time'
      path: '/time'
      fullPath: '/app/tasks/time'
      preLoaderRoute: typeof AuthenticatedAppTasksTimeRouteImport
      parentRoute: typeof AuthenticatedAppTasksRoute
    }
    '/_authenticated/app/tasks/kanban': {
      id: '/_authenticated/app/tasks/kanban'
      path: '/kanban'
      fullPath: '/app/tasks/kanban'
      preLoaderRoute: typeof AuthenticatedAppTasksKanbanRouteImport
      parentRoute: typeof AuthenticatedAppTasksRoute
    }
    '/_authenticated/app/tasks/all': {
      id: '/_authenticated/app/tasks/all'
      path: '/all'
      fullPath: '/app/tasks/all'
      preLoaderRoute: typeof AuthenticatedAppTasksAllRouteImport
      parentRoute: typeof AuthenticatedAppTasksRoute
    }
    '/_authenticated/app/tasks/$id': {
      id: '/_authenticated/app/tasks/$id'
      path: '/$id'
      fullPath: '/app/tasks/$id'
      preLoaderRoute: typeof AuthenticatedAppTasksIdRouteImport
      parentRoute: typeof AuthenticatedAppTasksRoute
    }
    '/_authenticated/app/sprints/$id': {
      id: '/_authenticated/app/sprints/$id'
      path: '/$id'
      fullPath: '/app/sprints/$id'
      preLoaderRoute: typeof AuthenticatedAppSprintsIdRouteImport
      parentRoute: typeof AuthenticatedAppSprintsRoute
    }
    '/_authenticated/app/projects/workspace': {
      id: '/_authenticated/app/projects/workspace'
      path: '/workspace'
      fullPath: '/app/projects/workspace'
      preLoaderRoute: typeof AuthenticatedAppProjectsWorkspaceRouteImport
      parentRoute: typeof AuthenticatedAppProjectsRoute
    }
    '/_authenticated/app/projects/templates': {
      id: '/_authenticated/app/projects/templates'
      path: '/templates'
      fullPath: '/app/projects/templates'
      preLoaderRoute: typeof AuthenticatedAppProjectsTemplatesRouteImport
      parentRoute: typeof AuthenticatedAppProjectsRoute
    }
    '/_authenticated/app/projects/clients': {
      id: '/_authenticated/app/projects/clients'
      path: '/clients'
      fullPath: '/app/projects/clients'
      preLoaderRoute: typeof AuthenticatedAppProjectsClientsRouteImport
      parentRoute: typeof AuthenticatedAppProjectsRoute
    }
    '/_authenticated/app/projects/all': {
      id: '/_authenticated/app/projects/all'
      path: '/all'
      fullPath: '/app/projects/all'
      preLoaderRoute: typeof AuthenticatedAppProjectsAllRouteImport
      parentRoute: typeof AuthenticatedAppProjectsRoute
    }
    '/_authenticated/app/projects/$id': {
      id: '/_authenticated/app/projects/$id'
      path: '/$id'
      fullPath: '/app/projects/$id'
      preLoaderRoute: typeof AuthenticatedAppProjectsIdRouteImport
      parentRoute: typeof AuthenticatedAppProjectsRoute
    }
    '/_authenticated/app/notifications/preferences': {
      id: '/_authenticated/app/notifications/preferences'
      path: '/app/notifications/preferences'
      fullPath: '/app/notifications/preferences'
      preLoaderRoute: typeof AuthenticatedAppNotificationsPreferencesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/hr/organization': {
      id: '/_authenticated/app/hr/organization'
      path: '/organization'
      fullPath: '/app/hr/organization'
      preLoaderRoute: typeof AuthenticatedAppHrOrganizationRouteImport
      parentRoute: typeof AuthenticatedAppHrRoute
    }
    '/_authenticated/app/hr/onboarding': {
      id: '/_authenticated/app/hr/onboarding'
      path: '/onboarding'
      fullPath: '/app/hr/onboarding'
      preLoaderRoute: typeof AuthenticatedAppHrOnboardingRouteImport
      parentRoute: typeof AuthenticatedAppHrRoute
    }
    '/_authenticated/app/hr/offboarding': {
      id: '/_authenticated/app/hr/offboarding'
      path: '/offboarding'
      fullPath: '/app/hr/offboarding'
      preLoaderRoute: typeof AuthenticatedAppHrOffboardingRouteImport
      parentRoute: typeof AuthenticatedAppHrRoute
    }
    '/_authenticated/app/hr/leave': {
      id: '/_authenticated/app/hr/leave'
      path: '/leave'
      fullPath: '/app/hr/leave'
      preLoaderRoute: typeof AuthenticatedAppHrLeaveRouteImport
      parentRoute: typeof AuthenticatedAppHrRoute
    }
    '/_authenticated/app/hr/invitations': {
      id: '/_authenticated/app/hr/invitations'
      path: '/invitations'
      fullPath: '/app/hr/invitations'
      preLoaderRoute: typeof AuthenticatedAppHrInvitationsRouteImport
      parentRoute: typeof AuthenticatedAppHrRoute
    }
    '/_authenticated/app/hr/documents': {
      id: '/_authenticated/app/hr/documents'
      path: '/documents'
      fullPath: '/app/hr/documents'
      preLoaderRoute: typeof AuthenticatedAppHrDocumentsRouteImport
      parentRoute: typeof AuthenticatedAppHrRoute
    }
    '/_authenticated/app/hr/audit': {
      id: '/_authenticated/app/hr/audit'
      path: '/audit'
      fullPath: '/app/hr/audit'
      preLoaderRoute: typeof AuthenticatedAppHrAuditRouteImport
      parentRoute: typeof AuthenticatedAppHrRoute
    }
    '/_authenticated/app/hr/announcements': {
      id: '/_authenticated/app/hr/announcements'
      path: '/announcements'
      fullPath: '/app/hr/announcements'
      preLoaderRoute: typeof AuthenticatedAppHrAnnouncementsRouteImport
      parentRoute: typeof AuthenticatedAppHrRoute
    }
    '/_authenticated/app/eod/history': {
      id: '/_authenticated/app/eod/history'
      path: '/app/eod/history'
      fullPath: '/app/eod/history'
      preLoaderRoute: typeof AuthenticatedAppEodHistoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/dependencies/manager': {
      id: '/_authenticated/app/dependencies/manager'
      path: '/manager'
      fullPath: '/app/dependencies/manager'
      preLoaderRoute: typeof AuthenticatedAppDependenciesManagerRouteImport
      parentRoute: typeof AuthenticatedAppDependenciesRoute
    }
    '/_authenticated/app/dependencies/$id': {
      id: '/_authenticated/app/dependencies/$id'
      path: '/$id'
      fullPath: '/app/dependencies/$id'
      preLoaderRoute: typeof AuthenticatedAppDependenciesIdRouteImport
      parentRoute: typeof AuthenticatedAppDependenciesRoute
    }
    '/_authenticated/app/attendance/team': {
      id: '/_authenticated/app/attendance/team'
      path: '/app/attendance/team'
      fullPath: '/app/attendance/team'
      preLoaderRoute: typeof AuthenticatedAppAttendanceTeamRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/analytics/team': {
      id: '/_authenticated/app/analytics/team'
      path: '/team'
      fullPath: '/app/analytics/team'
      preLoaderRoute: typeof AuthenticatedAppAnalyticsTeamRouteImport
      parentRoute: typeof AuthenticatedAppAnalyticsRoute
    }
    '/_authenticated/app/analytics/saved': {
      id: '/_authenticated/app/analytics/saved'
      path: '/saved'
      fullPath: '/app/analytics/saved'
      preLoaderRoute: typeof AuthenticatedAppAnalyticsSavedRouteImport
      parentRoute: typeof AuthenticatedAppAnalyticsRoute
    }
    '/_authenticated/app/analytics/hr': {
      id: '/_authenticated/app/analytics/hr'
      path: '/hr'
      fullPath: '/app/analytics/hr'
      preLoaderRoute: typeof AuthenticatedAppAnalyticsHrRouteImport
      parentRoute: typeof AuthenticatedAppAnalyticsRoute
    }
    '/_authenticated/app/analytics/executive': {
      id: '/_authenticated/app/analytics/executive'
      path: '/executive'
      fullPath: '/app/analytics/executive'
      preLoaderRoute: typeof AuthenticatedAppAnalyticsExecutiveRouteImport
      parentRoute: typeof AuthenticatedAppAnalyticsRoute
    }
    '/_authenticated/app/hr/employees/': {
      id: '/_authenticated/app/hr/employees/'
      path: '/employees'
      fullPath: '/app/hr/employees/'
      preLoaderRoute: typeof AuthenticatedAppHrEmployeesIndexRouteImport
      parentRoute: typeof AuthenticatedAppHrRoute
    }
    '/_authenticated/app/projects/clients/$id': {
      id: '/_authenticated/app/projects/clients/$id'
      path: '/$id'
      fullPath: '/app/projects/clients/$id'
      preLoaderRoute: typeof AuthenticatedAppProjectsClientsIdRouteImport
      parentRoute: typeof AuthenticatedAppProjectsClientsRoute
    }
    '/_authenticated/app/hr/employees/$id': {
      id: '/_authenticated/app/hr/employees/$id'
      path: '/employees/$id'
      fullPath: '/app/hr/employees/$id'
      preLoaderRoute: typeof AuthenticatedAppHrEmployeesIdRouteImport
      parentRoute: typeof AuthenticatedAppHrRoute
    }
  }
}

interface AuthenticatedAppAnalyticsRouteChildren {
  AuthenticatedAppAnalyticsExecutiveRoute: typeof AuthenticatedAppAnalyticsExecutiveRoute
  AuthenticatedAppAnalyticsHrRoute: typeof AuthenticatedAppAnalyticsHrRoute
  AuthenticatedAppAnalyticsSavedRoute: typeof AuthenticatedAppAnalyticsSavedRoute
  AuthenticatedAppAnalyticsTeamRoute: typeof AuthenticatedAppAnalyticsTeamRoute
  AuthenticatedAppAnalyticsIndexRoute: typeof AuthenticatedAppAnalyticsIndexRoute
}

const AuthenticatedAppAnalyticsRouteChildren: AuthenticatedAppAnalyticsRouteChildren =
  {
    AuthenticatedAppAnalyticsExecutiveRoute:
      AuthenticatedAppAnalyticsExecutiveRoute,
    AuthenticatedAppAnalyticsHrRoute: AuthenticatedAppAnalyticsHrRoute,
    AuthenticatedAppAnalyticsSavedRoute: AuthenticatedAppAnalyticsSavedRoute,
    AuthenticatedAppAnalyticsTeamRoute: AuthenticatedAppAnalyticsTeamRoute,
    AuthenticatedAppAnalyticsIndexRoute: AuthenticatedAppAnalyticsIndexRoute,
  }

const AuthenticatedAppAnalyticsRouteWithChildren =
  AuthenticatedAppAnalyticsRoute._addFileChildren(
    AuthenticatedAppAnalyticsRouteChildren,
  )

interface AuthenticatedAppDependenciesRouteChildren {
  AuthenticatedAppDependenciesIdRoute: typeof AuthenticatedAppDependenciesIdRoute
  AuthenticatedAppDependenciesManagerRoute: typeof AuthenticatedAppDependenciesManagerRoute
  AuthenticatedAppDependenciesIndexRoute: typeof AuthenticatedAppDependenciesIndexRoute
}

const AuthenticatedAppDependenciesRouteChildren: AuthenticatedAppDependenciesRouteChildren =
  {
    AuthenticatedAppDependenciesIdRoute: AuthenticatedAppDependenciesIdRoute,
    AuthenticatedAppDependenciesManagerRoute:
      AuthenticatedAppDependenciesManagerRoute,
    AuthenticatedAppDependenciesIndexRoute:
      AuthenticatedAppDependenciesIndexRoute,
  }

const AuthenticatedAppDependenciesRouteWithChildren =
  AuthenticatedAppDependenciesRoute._addFileChildren(
    AuthenticatedAppDependenciesRouteChildren,
  )

interface AuthenticatedAppHrRouteChildren {
  AuthenticatedAppHrAnnouncementsRoute: typeof AuthenticatedAppHrAnnouncementsRoute
  AuthenticatedAppHrAuditRoute: typeof AuthenticatedAppHrAuditRoute
  AuthenticatedAppHrDocumentsRoute: typeof AuthenticatedAppHrDocumentsRoute
  AuthenticatedAppHrInvitationsRoute: typeof AuthenticatedAppHrInvitationsRoute
  AuthenticatedAppHrLeaveRoute: typeof AuthenticatedAppHrLeaveRoute
  AuthenticatedAppHrOffboardingRoute: typeof AuthenticatedAppHrOffboardingRoute
  AuthenticatedAppHrOnboardingRoute: typeof AuthenticatedAppHrOnboardingRoute
  AuthenticatedAppHrOrganizationRoute: typeof AuthenticatedAppHrOrganizationRoute
  AuthenticatedAppHrIndexRoute: typeof AuthenticatedAppHrIndexRoute
  AuthenticatedAppHrEmployeesIdRoute: typeof AuthenticatedAppHrEmployeesIdRoute
  AuthenticatedAppHrEmployeesIndexRoute: typeof AuthenticatedAppHrEmployeesIndexRoute
}

const AuthenticatedAppHrRouteChildren: AuthenticatedAppHrRouteChildren = {
  AuthenticatedAppHrAnnouncementsRoute: AuthenticatedAppHrAnnouncementsRoute,
  AuthenticatedAppHrAuditRoute: AuthenticatedAppHrAuditRoute,
  AuthenticatedAppHrDocumentsRoute: AuthenticatedAppHrDocumentsRoute,
  AuthenticatedAppHrInvitationsRoute: AuthenticatedAppHrInvitationsRoute,
  AuthenticatedAppHrLeaveRoute: AuthenticatedAppHrLeaveRoute,
  AuthenticatedAppHrOffboardingRoute: AuthenticatedAppHrOffboardingRoute,
  AuthenticatedAppHrOnboardingRoute: AuthenticatedAppHrOnboardingRoute,
  AuthenticatedAppHrOrganizationRoute: AuthenticatedAppHrOrganizationRoute,
  AuthenticatedAppHrIndexRoute: AuthenticatedAppHrIndexRoute,
  AuthenticatedAppHrEmployeesIdRoute: AuthenticatedAppHrEmployeesIdRoute,
  AuthenticatedAppHrEmployeesIndexRoute: AuthenticatedAppHrEmployeesIndexRoute,
}

const AuthenticatedAppHrRouteWithChildren =
  AuthenticatedAppHrRoute._addFileChildren(AuthenticatedAppHrRouteChildren)

interface AuthenticatedAppProjectsClientsRouteChildren {
  AuthenticatedAppProjectsClientsIdRoute: typeof AuthenticatedAppProjectsClientsIdRoute
}

const AuthenticatedAppProjectsClientsRouteChildren: AuthenticatedAppProjectsClientsRouteChildren =
  {
    AuthenticatedAppProjectsClientsIdRoute:
      AuthenticatedAppProjectsClientsIdRoute,
  }

const AuthenticatedAppProjectsClientsRouteWithChildren =
  AuthenticatedAppProjectsClientsRoute._addFileChildren(
    AuthenticatedAppProjectsClientsRouteChildren,
  )

interface AuthenticatedAppProjectsRouteChildren {
  AuthenticatedAppProjectsIdRoute: typeof AuthenticatedAppProjectsIdRoute
  AuthenticatedAppProjectsAllRoute: typeof AuthenticatedAppProjectsAllRoute
  AuthenticatedAppProjectsClientsRoute: typeof AuthenticatedAppProjectsClientsRouteWithChildren
  AuthenticatedAppProjectsTemplatesRoute: typeof AuthenticatedAppProjectsTemplatesRoute
  AuthenticatedAppProjectsWorkspaceRoute: typeof AuthenticatedAppProjectsWorkspaceRoute
  AuthenticatedAppProjectsIndexRoute: typeof AuthenticatedAppProjectsIndexRoute
}

const AuthenticatedAppProjectsRouteChildren: AuthenticatedAppProjectsRouteChildren =
  {
    AuthenticatedAppProjectsIdRoute: AuthenticatedAppProjectsIdRoute,
    AuthenticatedAppProjectsAllRoute: AuthenticatedAppProjectsAllRoute,
    AuthenticatedAppProjectsClientsRoute:
      AuthenticatedAppProjectsClientsRouteWithChildren,
    AuthenticatedAppProjectsTemplatesRoute:
      AuthenticatedAppProjectsTemplatesRoute,
    AuthenticatedAppProjectsWorkspaceRoute:
      AuthenticatedAppProjectsWorkspaceRoute,
    AuthenticatedAppProjectsIndexRoute: AuthenticatedAppProjectsIndexRoute,
  }

const AuthenticatedAppProjectsRouteWithChildren =
  AuthenticatedAppProjectsRoute._addFileChildren(
    AuthenticatedAppProjectsRouteChildren,
  )

interface AuthenticatedAppSprintsRouteChildren {
  AuthenticatedAppSprintsIdRoute: typeof AuthenticatedAppSprintsIdRoute
  AuthenticatedAppSprintsIndexRoute: typeof AuthenticatedAppSprintsIndexRoute
}

const AuthenticatedAppSprintsRouteChildren: AuthenticatedAppSprintsRouteChildren =
  {
    AuthenticatedAppSprintsIdRoute: AuthenticatedAppSprintsIdRoute,
    AuthenticatedAppSprintsIndexRoute: AuthenticatedAppSprintsIndexRoute,
  }

const AuthenticatedAppSprintsRouteWithChildren =
  AuthenticatedAppSprintsRoute._addFileChildren(
    AuthenticatedAppSprintsRouteChildren,
  )

interface AuthenticatedAppTasksRouteChildren {
  AuthenticatedAppTasksIdRoute: typeof AuthenticatedAppTasksIdRoute
  AuthenticatedAppTasksAllRoute: typeof AuthenticatedAppTasksAllRoute
  AuthenticatedAppTasksKanbanRoute: typeof AuthenticatedAppTasksKanbanRoute
  AuthenticatedAppTasksTimeRoute: typeof AuthenticatedAppTasksTimeRoute
  AuthenticatedAppTasksIndexRoute: typeof AuthenticatedAppTasksIndexRoute
}

const AuthenticatedAppTasksRouteChildren: AuthenticatedAppTasksRouteChildren = {
  AuthenticatedAppTasksIdRoute: AuthenticatedAppTasksIdRoute,
  AuthenticatedAppTasksAllRoute: AuthenticatedAppTasksAllRoute,
  AuthenticatedAppTasksKanbanRoute: AuthenticatedAppTasksKanbanRoute,
  AuthenticatedAppTasksTimeRoute: AuthenticatedAppTasksTimeRoute,
  AuthenticatedAppTasksIndexRoute: AuthenticatedAppTasksIndexRoute,
}

const AuthenticatedAppTasksRouteWithChildren =
  AuthenticatedAppTasksRoute._addFileChildren(
    AuthenticatedAppTasksRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedAppAdminRoute: typeof AuthenticatedAppAdminRoute
  AuthenticatedAppAnalyticsRoute: typeof AuthenticatedAppAnalyticsRouteWithChildren
  AuthenticatedAppAuditRoute: typeof AuthenticatedAppAuditRoute
  AuthenticatedAppCheckInRoute: typeof AuthenticatedAppCheckInRoute
  AuthenticatedAppDependenciesRoute: typeof AuthenticatedAppDependenciesRouteWithChildren
  AuthenticatedAppExecutiveRoute: typeof AuthenticatedAppExecutiveRoute
  AuthenticatedAppHrRoute: typeof AuthenticatedAppHrRouteWithChildren
  AuthenticatedAppIntegrationsRoute: typeof AuthenticatedAppIntegrationsRoute
  AuthenticatedAppManagerRoute: typeof AuthenticatedAppManagerRoute
  AuthenticatedAppMiddayRoute: typeof AuthenticatedAppMiddayRoute
  AuthenticatedAppProjectsRoute: typeof AuthenticatedAppProjectsRouteWithChildren
  AuthenticatedAppReportReviewRoute: typeof AuthenticatedAppReportReviewRoute
  AuthenticatedAppSprintsRoute: typeof AuthenticatedAppSprintsRouteWithChildren
  AuthenticatedAppTasksRoute: typeof AuthenticatedAppTasksRouteWithChildren
  AuthenticatedAppIndexRoute: typeof AuthenticatedAppIndexRoute
  AuthenticatedAppAttendanceTeamRoute: typeof AuthenticatedAppAttendanceTeamRoute
  AuthenticatedAppEodHistoryRoute: typeof AuthenticatedAppEodHistoryRoute
  AuthenticatedAppNotificationsPreferencesRoute: typeof AuthenticatedAppNotificationsPreferencesRoute
  AuthenticatedAppAttendanceIndexRoute: typeof AuthenticatedAppAttendanceIndexRoute
  AuthenticatedAppEodIndexRoute: typeof AuthenticatedAppEodIndexRoute
  AuthenticatedAppNotificationsIndexRoute: typeof AuthenticatedAppNotificationsIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedAppAdminRoute: AuthenticatedAppAdminRoute,
  AuthenticatedAppAnalyticsRoute: AuthenticatedAppAnalyticsRouteWithChildren,
  AuthenticatedAppAuditRoute: AuthenticatedAppAuditRoute,
  AuthenticatedAppCheckInRoute: AuthenticatedAppCheckInRoute,
  AuthenticatedAppDependenciesRoute:
    AuthenticatedAppDependenciesRouteWithChildren,
  AuthenticatedAppExecutiveRoute: AuthenticatedAppExecutiveRoute,
  AuthenticatedAppHrRoute: AuthenticatedAppHrRouteWithChildren,
  AuthenticatedAppIntegrationsRoute: AuthenticatedAppIntegrationsRoute,
  AuthenticatedAppManagerRoute: AuthenticatedAppManagerRoute,
  AuthenticatedAppMiddayRoute: AuthenticatedAppMiddayRoute,
  AuthenticatedAppProjectsRoute: AuthenticatedAppProjectsRouteWithChildren,
  AuthenticatedAppReportReviewRoute: AuthenticatedAppReportReviewRoute,
  AuthenticatedAppSprintsRoute: AuthenticatedAppSprintsRouteWithChildren,
  AuthenticatedAppTasksRoute: AuthenticatedAppTasksRouteWithChildren,
  AuthenticatedAppIndexRoute: AuthenticatedAppIndexRoute,
  AuthenticatedAppAttendanceTeamRoute: AuthenticatedAppAttendanceTeamRoute,
  AuthenticatedAppEodHistoryRoute: AuthenticatedAppEodHistoryRoute,
  AuthenticatedAppNotificationsPreferencesRoute:
    AuthenticatedAppNotificationsPreferencesRoute,
  AuthenticatedAppAttendanceIndexRoute: AuthenticatedAppAttendanceIndexRoute,
  AuthenticatedAppEodIndexRoute: AuthenticatedAppEodIndexRoute,
  AuthenticatedAppNotificationsIndexRoute:
    AuthenticatedAppNotificationsIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  UnauthorizedRoute: UnauthorizedRoute,
  AuthAcceptInvitationRoute: AuthAcceptInvitationRoute,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthSessionExpiredRoute: AuthSessionExpiredRoute,
  AuthVerifyEmailRoute: AuthVerifyEmailRoute,
  AuthIndexRoute: AuthIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
